/**
 * \brief Class that represents a possibility.
 *
 * \details  A possibility is one of the possible states description for EFP. It represent a single state in the
 *  mA^rho language.
 * 
 * @see pworld and pstore.
 *
 * \todo general: the && parameter in set (move) and in other places, is it better?
 *
 * \copyright GNU Public License.
 *
 * \author Francesco Fabiano.
 * \date September 16, 2019
 */
#pragma once

#include "pworld.h"
#include "pstore.h"

#include "../../utilities/define.h"
#include "../../domain/initially.h"
#include "../../actions/action.h"

class pstate
{
private:

    /** \brief Int used to differentiate the partial \ref pstate generated by partial obsv.*/
    unsigned int m_max_depth = 0;
    /** \brief The set containing a pointer to each world of the structure.
     *
     *  \todo: forse basta solo m_pointed.
     *
     * @see pworld and pstore.*/
    pworld_ptr_set m_worlds;
    /** \brief The pointer to the *pointed world*.
     * 
     * @see pworld and pstore.*/
    pworld_ptr m_pointed;
    /** \brief The beliefs of each \ref agent in every \ref pworld.
     *
     * @see pworld.*/
    pworld_transitive_map m_beliefs;
    /** \brief Function that checks the entailment of a \ref fluent in a given \ref pworld.
     *     @see \ref pworld::entails(fluent) const
     *  
     * @param[in] to_check: the \ref fluent that has to be checked if entailed in \p world.
     * @param[in] world: the pointer to the  \ref pworld where to check the entailment.
     *
     * @return true: \p to_check is entailed in \p world;
     * @return false: \p -to_check is entailed in \p world.*/
    bool entails(fluent to_check, pworld_ptr world) const;
    /**
     *\brief Function that checks the entailment of a conjunctive set of \ref fluent in a given \ref pworld.
     *     @see \ref pworld::entails(const fluent_set &) const
     *  
     * @param[in] to_check: the conjunctive set of \ref fluent that has to be checked if entailed in \p world.
     * @param[in] world: the pointer to the  \ref pworld where to check the entailment.
     *
     * @return true: \p to_check is entailed in \p world;
     * @return false: \p -to_check is entailed in \p world.*/
    bool entails(const fluent_set & to_check, pworld_ptr world) const;
    /**
     *\brief Function that checks the entailment of a conjunctive set of \ref fluent in a given \ref pworld.
     *     @see \ref pworld::entails(const fluent_formula &) const
     *  
     * @param[in] to_check: the DNF \ref fluent_formula that has to be checked if entailed in \p world.
     * @param[in] world: the pointer to the \ref pworld where to check the entailment.
     *
     * @return true: \p to_check is entailed in \p world;
     * @return false: \p -to_check is entailed in \p world.*/
    bool entails(const fluent_formula & to_check, pworld_ptr world) const;

    /** \brief Function that checks the entailment of a \ref belief_formula.
     * 
     * The concept of entailment of a \ref belief_formula is related to reachability
     * and so an initial state is required, the given \ref pworld \p world is the starting point
     * (it simulates the pointed world) where the entailment check starts from. The
     * world needs to be parametric to not create a new \ref pstate for every iteration of the formula;
     * now we can just change the starting point and keep the same \ref pstate when testing, for example,
     * *nested knowledge*. The function is private because the entailment always starts from the \ref m_pointed and then
     * moves to the reachable (with the operators) \ref pworld.
     *  
     * @see \ref belief_formula and entails(const belief_formula &) const.
     * 
     * @param[in] to_check: the \ref belief_formula that has to be checked if entailed from \p world.
     * @param[in] world: the pointer to the \ref pworld where to start to check the entailment.
     *
     * @return true: \p to_check is entailed starting from \p world;
     * @return false: \p -to_check is entailed starting from \p world.
     * 
     * \todo self-loop?*/
    bool entails(const belief_formula & to_check, pworld_ptr world) const;
    /** \brief Function that checks the entailment of a \ref belief_formula on several possible starting points.
     * 
     * This function eases the task to check the entailment from several starting \ref pworld simultaneously.
     * This happens when we want to check the transitive closure of the \ref agent ag  to test the formula B(ag, phi).
     * 
     * @see belief_formula.
     * 
     * @param[in] to_check: the \ref belief_formula that has to be checked if entailed from \p world.
     * @param[in] worlds: the pointers to the set of \ref pworld where to start to check the entailment.
     *
     * @return true: \p to_check is entailed starting from all the \ref pworld in \p worlds;
     * @return false: \p -to_check is entailed starting from all the \ref pworld in \p worlds.
     * 
     * \todo self-loop?*/
    bool entails(const belief_formula & to_check, const pworld_ptr_set & worlds) const;


    /** \brief Function that checks the entailment of a \ref formula_list (CNF of \ref belief_formula).
     * 
     * 
     * @param[in] to_check: the \ref formula_list that has to be checked if entailed starting from from \p world.
     * @param[in] world: the pointer to the \ref pworld where to start to check the entailment.
     *
     * @return true: \p to_check is entailed starting from \p world;
     * @return false: \p -to_check is entailed starting from \p world.
     * 
     * \todo self-loop?*/
    bool entails(const formula_list & to_check, pworld_ptr world) const;

    /** \brief Function that returns all the reachable \ref pworld given the \ref agent and the staring \ref pworld.
     * 
     * This function finds all the world that are transitively reachable from the starting world following
     * the edges labelled with the given \ref agent. It returns all the worlds where is necessary to check if
     * *phi* is entailed in order to verify B(\p ag, *phi*) and \p world is the starting point.
     * 
     * @see \ref belief_formula.
     * 
     * @param[in] ag: the label of the \ref kedge that the function follows to check the transitivity.
     * @param[in] world: the pointers to the set of \ref pworld where to start to check the entailment.
     *
     * @return a set of pointers to all the reachable worlds.
     *
     * 
     * \todo self-loop?*/
    const pworld_ptr_set get_B_reachable_worlds(agent ag, pworld_ptr world) const;

    /** \brief Function that returns all the reachable \ref pworld given the \ref agent and the staring \ref pworld.
     * 
     * This function modify the parameter so it's easy to check if a fixed point is reached.
     * This is useful for the operator C. Otherwise its better to use \ref get_B_reachable_worlds(agent, pworld_ptr) const.
     * 
     * @see belief_formula, get_B_reachable_worlds(agent, pworld_ptr) const and get_C_reachable_worlds(const agent_set &, pworld_ptr world) const.
     * 
     * @param[in] ag: the label of the \ref kedge that the function follows to check the transitivity.
     * @param[in] world: the pointers to the set of \ref pworld where to start to check the entailment.
     *
     * @param[out] reached: the set of pointers to all the reachable worlds.
     *
     * 
     * \todo self-loop?*/
    bool get_B_reachable_worlds(agent ag, pworld_ptr world, pworld_ptr_set& reached) const;

    /** \brief Function that returns all the reachable \ref pworld given a set of \ref agent and the staring \ref pworld.
     * 
     * This function applies get_E_reachable_worlds(agent , pworld_ptr) with all the agents inside the
     * given set and return the union of the reached \ref pworld. It returns all the worlds where is necessary to check if
     * *phi* is entailed in order to verify E(\p ags, *phi*) and \p world is the starting point.
     * 
     * @see \ref belief_formula and get_B_reachable_worlds(agent, pworld_ptr).
     * 
     * @param[in] ags: the set of label of the \ref kedge that the function follows to check the transitivity.
     * @param[in] world: the pointers to the set of \ref pworld where to start to check the entailment.
     *
     * @return a set of pointers to all the reachable worlds.
     *
     * 
     * \todo self-loop?*/
    const pworld_ptr_set get_E_reachable_worlds(const agent_set & ags, pworld_ptr world) const;

    /** \brief Function that returns all the reachable \ref pworld given a set of \ref agent and the staring \ref pworld.
     * 
     * This function modify the parameter so it's easy to check if a fixed point is reached.
     * This is useful for the operator C. Otherwise its better to use \ref get_E_reachable_worlds(const agent_set &, pworld_ptr) const.
     * 
     * @see \ref belief_formula, get_B_reachable_worlds(agent, pworld_ptr, pworld_ptr_set) const and get_C_reachable_worlds(const agent_set &, pworld_ptr world) const.
     * 
     * @param[in] ags: the set of label of the \ref kedge that the function follows to check the transitivity.
     * @param[in] world: the pointers to the set of \ref pworld where to start to check the entailment.
     *
     * @param[out] reached: the set of pointers to all the reachable worlds.
     *
     * 
     * \todo self-loop?*/
    bool get_E_reachable_worlds(const agent_set &ags, pworld_ptr world, pworld_ptr_set& reached) const;

    /** \brief Function that returns all the reachable \ref pworld (in the *Common Knowledge* sense) given a \ref agent and the staring \ref pworld.
     * 
     * This function applies get_E_reachable_worlds(const agent_set &, pworld_ptr) on its on result until a fixed point is found.
     * It returns all the worlds where is necessary to check if *phi* is entailed in order to verify C(\p ags, *phi*) and \p world is the starting point.
     * 
     * @see \ref belief_formula, and get_E_reachable_worlds(const agent_set &, pworld_ptr world).
     * 
     * @param[in] ags: the set of label of the \ref kedge that the function follows to check the *Common Knowledge* reachability.
     * @param[in] world: the pointers to the set of \ref pworld where to start to check the entailment.
     *
     * @return a set of pointers to all the reachable worlds.
     * 
     * \todo self-loop?*/
    const pworld_ptr_set get_C_reachable_worlds(const agent_set &, pworld_ptr world) const;

    /** \brief Function that builds the initial Kripke structure given the initial conditions in a structural way.
     *
     *         -# Compute the set of *phi* not know by \ref agent ag for each \ref agent;
     *         -# for each set compute the all the consistent \ref pworld where *phi* changes;
     *         -# create a \ref kedge between all this \ref pworld (transitively closed) labeled with ag;
     *         -# link all the classes of \ref pworld with an ongoing \ref kedge labeled with the ag of the reaching class.
     * 
     * @see pworld, kedge and initially.*/
    void build_initial_structural();

    /** \brief Function that builds the initial Kripke structure given the initial conditions pruning from a complete K structure.
     *
     *    - Thanks to \ref generate_initial_pworlds we generate all the possible worlds.
     *  We than store all the ones that respect \p ini_conditions *this* and all the other only in \ref pstore.
     * 
     * @see pworld, kedge and initially.
     *  
     * \todo If this method is the one is implemented the add functions in \ref pstore must be changed to not create the object
     *       every time but just to retrieve the object since all of them are already created.*/
    void build_initial_prune();
    /** \brief Function used to build all the possible permutations of the \ref domain's \ref fluent.
     *  
     * The function creates all the permutation recursively and adds to *this* only the ones that respect \p ini_conditions.
     * All the other ones are stored in \ref pstore for future uses.
     * 
     * @param[out] permutation: the permutation in construction.
     * @param[in] index: the index of the \ref fluent to add.*/

    void generate_initial_pworlds(fluent_set& permutation, int index);
    /** \brief Function check if the \ref pworld respect the initial conditions and adds it to *this* if it does.
     *  
     * The function checks if the \ref pworld created by \ref generate_initial_pworlds(fluent_set&, int)
     * entails the initial conditions and:
     * - If it does the \ref pworld is added to *this* (and to \ref pstore).
     * - If it doesn't the \ref pworld is added only to \ref pstore.
     * 
     * @param[in] possible_add: the \ref pworld to check.*/
    void add_initial_pworld(const pworld & possible_add);

    /** \brief Function used to build the \ref kedge of the initial \ref pstate.
     *  
     * The function creates all the edges and adds to *this* only the ones that respect \p ini_conditions.
     * All the other ones are stored in \ref pstore for future usees.*/
    void generate_initial_pedges();
    /** \brief Function that removes the belief of \ref agent "ag" from \ref pworld "from" to \ref pworld "to".
     * 
     * @param[in] from: the \ref pworld in which \ref agent "ag" currently is
     * @param[in] to: the \ref pworld to remove
     * @param[in] ag: the \ref agent.*/
    void remove_edge(pworld_ptr & from, const pworld & to, const agent ag);
    /** \brief Function that removes the \ref pedge(s) that imply that \p ag is ignorant about \p known_ff from *this*.
     *  
     * @param[in] known_ff: the \ref fluent_formula known by \p ag.
     * @param[in] ag: the \ref agent that knows \p known_ff.*/
    void remove_initial_pedge(const fluent_formula &known_ff, agent ag);
    /** \brief Function check if a belief_formula removes some edges from the initial state.
     *  
     * For example whenever is B(i, *phi*) \/ B(i, -*phi*) is necessary to remove the edges
     * labeled with i that link \ref pworld that entails *phi* and \ref pworld -*phi*.
     * 
     * @param[in] to_check: the \ref belief_formula to check.*/
    void remove_initial_pedge_bf(const belief_formula &to_check);

    void add_world(const pworld & to_add);

    /** \brief Function that adds the belief of agent "ag" for the \ref pworld "pw" *this*.
     *
     * @param[in] from: the \ref pworld in which \ref agent "ag" currently is
     * @param[in] to: the \ref pworld believed from \ref agent "ag"
     * @param[in] ag: the \ref agent.*/
    void add_edge(pworld_ptr & from, pworld_ptr & to, agent ag);

    /** \brief Function that return the set of \ref agent that entails the obs condition.
     *
     * @param[in] map: the map that contains the tuples to check for entailment.
     * @param[in] start: the world to set as pointed to check the entailment.
     * @return the effects that are feasible in *this* with \p start as pointed world*.*/
    agent_set get_agents_if_entailed(const observability_map & map, const pworld_ptr & start) const;

    /** \brief Function that return the \ref fluent_formula (effect) that entails the exe condition.
     *  
     * @param[in] map: the map that contains the tuples to check for entailment.
     * @param[in] start: the world to set as pointed to check the entailment.
     * @return the effects that are feasible in *this* with \p start as pointed world*.*/
    fluent_formula get_effects_if_entailed(const effects_map & map, const pworld_ptr & start) const;

    /** \brief Function that calculates the effect of the \ref action "act" to the \ref pworld "world"
     *
     * @param[in] act: the \ref ONTIC action to be applied on *this*.
     * @param[in] world: the world where we are currently executing the \ref action.
     * @param[in] it_eff: an iterator for fluent formulas.*/

    void execute_ontic_effects(const action &act, pworld_ptr &world) const;
    /** \brief Function that explores the unvisited \ref pworld encountered inside the agents' beliefs.
     *
     * We visit the worlds believed to be true by some fully observant \ref agent and we push them into "to_visit" if the transition function were not already applied to them.
     * We also keep track of the agents' belief to be updated later (\ref backtrack_remaining_beliefs).
     *
     * @param[in] act: the \ref action to be applied on *this*.
     * @param[in] ret: the \ref pstate resulting from the \ref action.
     * @param[in] world: the world being currently calculated.
     * @param[in] current_pmap: the \ref pworld_map of currently visited \ref pworld.
     * @param[in] to_visit: the \ref pworld_queue of \ref pworld yet to be considered.
     * @param[in] calculated: a map that keeps track of the results of the transition function.
     * @param[in] to_backtrack: a vector of tuples (pw1, pw2, ag) that represents the agents' beliefs to be updated later.
     * @param[in] p_obs_beliefs: represents the beliefs of the partially observant agents (in \ref SENSING/\ref ANNOUNCEMENT actions) about the \ref pworld that results from the negated \ref action.
     * @param[in] fully_obs_agents: the fully observant \ref agent set.
     * @param[in] action_type: the type of the action being performed.*/
    void explore_unvisited_pworlds(const action &act, pstate &ret, pworld_ptr &world, pworld_map &current_pmap, pworld_queue &to_visit, transition_map &calculated, beliefs_vector &to_backtrack, beliefs_vector &p_obs_beliefs, agent_set &fully_obs_agents, agent_set &oblivious_obs_agents) const;
    /** \brief Function that updates the agents' beliefs recorded into "to_backtrack".
     *
     * @param[in] ret: the \ref pstate resulting from the \ref action.
     * @param[in] calculated: a map that links the \ref pworld of *this* to their counterpart w.r.t. the transition function.
     * @param[in] to_backtrack: a vector of tuples (pw1, pw2, ag) that represent that in \ref pworld pw1 the \agent ag believes that the \ref \pworld pw2 is possible.
     * @param[in] p_obs_beliefs: represents the beliefs of the partially observant agents (in \ref SENSING/\ref ANNOUNCEMENT actions) about the \ref pworld that results from the negated \ref action.*/
    void backtrack_remaining_beliefs(pstate &ret, transition_map &calculated, beliefs_vector &to_backtrack, beliefs_vector &p_obs_beliefs) const;

    /** \brief Function that applies the transition function for the \ref action effect on *this* implementing the possibilities semantic.
     *
     * @param act: the \ref action to be applied on *this*.
     * @param ret: the \ref pstate resulting from the \ref action.
     * @param fully_obs_agents: the fully observant \ref agent set.
     * @param oblivious_obs_agents: the oblivious \ref agent set.*/
    void execute_action(const action &act, pstate &ret, agent_set &fully_obs_agents, agent_set &oblivious_obs_agents) const;
    /** \brief Function that applies the transition function for a \ref ONTIC \ref action effect on *this* implementing the possibilities semantic.
     *
     * The transition function is applied accordingly to mA^rho. Check the paper for more information.
     *
     * @see action.
     *
     * @param[in] act: the \ref ONTIC action to be applied on *this*.
     * @return the \ref pstate that results after the execution.*/
    pstate execute_ontic(const action &act) const;
    /** \brief Function that applies the transition function for a \ref SENSING \ref action effect on *this* implementing the possibilities semantic.
     *
     * The transition function is applied accordingly to mA^rho. Check the paper for more information.
     *
     * @see action.
     *
     * @param[in] act: the \ref SENSING action to be applied on *this*.
     * @return the \ref pstate that results after the execution.*/
    pstate execute_sensing(const action &act) const;
    /** \brief Function that applies the transition function for a \ref ANNOUNCEMENT \ref action effect on *this* implementing the possibilities semantic.
     *
     * The transition function is applied accordingly to mA^rho. Check the paper for more information.
     *
     * @see action.
     *
     * @param[in] act: the \ref ANNOUNCEMENT action to be applied on *this*.
     * @return the \ref pstate that results after the execution.*/
    pstate execute_announcement(const action &act) const;

public:

    /** \brief Setter of the field \ref m_worlds.
     *
     * @param[in] to_set: the \ref pworld_ptr_set to assign to \ref m_worlds.*/
    void set_worlds(const pworld_ptr_set & to_set);
    /** \brief Setter of the field \ref m_pointed.
     *
     * @param[in] to_set: the \ref pworld_ptr to assign to \ref m_pointed.*/
    void set_pointed(const pworld_ptr & to_set);
    /** \brief Setter of the field \ref m_max_depth.
     *
     * @param[in] to_set: the unsigned int to assign to \ref m_max_depth.*/
    void set_max_depth(unsigned int to_set);

    /** \brief Getter of the field \ref m_worlds.
     *
     * @return: the value of \ref m_worlds.*/
    const pworld_ptr_set & get_worlds() const;
    /** \brief Getter of the field \ref m_pointed.
     *
     * @return: the value of \ref m_pointed.*/
    const pworld_ptr & get_pointed() const;
    /** \brief Getter of the field \ref m_beliefs.
    *
    * @return: the value of \ref m_beliefs.*/
    const pworld_transitive_map & get_beliefs() const;
    /** \brief Getter of the field \ref m_max_depth.
     *
     * @return: the value of \ref m_max_depth.*/
    unsigned int get_max_depth() const;

    /** \brief Function that adds a \ref pworld to the Kripke structure represented by *this*.
     *
     * The \ref pworld is added. The structure only stores the pointer to the \ref pworld so
     * it is necessary to store the \ref pworld in \ref pstore.
     * It also uses \ref m_max_depth to avoid clashes with copies of \p world; it
     * represents the number to give to the pointer of \p word to differentiate it from its copies.
     * 
     * @see pworld and pstore.
     *  
     * @param[in] to_add: the \ref pworld that has to be added to *this*.
     * @return The a \ref pworld_ptr to the newly inserted \ref pworld.*/
    pworld_ptr add_rep_world(const pworld & to_add);
    /** \brief Function that adds a \ref pworld to the Kripke structure represented by *this* setting its repetition.
     *
     * The \ref pworld is added. The structure only stores the pointer to the \ref pworld so
     * it is necessary to store the \ref pworld in \ref pstore.
     * It also uses \p repetition to avoid clashes with copies of \p world; it
     * represents the number to give to the pointer of \p word to differentiate it from its copies.
     * 
     * @see pworld and pstore.
     *  
     * @param[in] to_add: the \ref pworld that has to be added to *this*.
     * @param[in] old_repetition: used to distinguish from same level of the structure but derived from different levels of the old structure.
     * @return The a \ref pworld_ptr to the newly inserted \ref pworld.*/
    pworld_ptr add_rep_world(const pworld & to_add, unsigned short old_repetition);
    /** \brief Function that adds a \ref pworld to the Kripke structure represented by *this* setting its repetition.
     *
     * The \ref pworld is added. The structure only stores the pointer to the \ref pworld so
     * it is necessary to store the \ref pworld in \ref pstore.
     * It also uses \p repetition to avoid clashes with copies of \p world; it
     * represents the number to give to the pointer of \p word to differentiate it from its copies.
     * 
     * @see pworld and pstore.
     *  
     * @param[in] to_add: the \ref pworld that has to be added to *this*.
     * @param[in] repetition: the is to distinguish from other levels of the structure.
     * @param[out] is_new: used to inidcate if the world was already present in the *this*.
     * @return The a \ref pworld_ptr to the newly inserted \ref pworld.*/
    pworld_ptr add_rep_world(const pworld & to_add, unsigned short repetition, bool& is_new);

    /** \brief Function that checks the entailment of a \ref fluent in *this*.
     *
     * The entailment of a \ref fluent in a pstate is true if the \ref fluent
     * is entailed by its pointed world (\ref m_pointed).
     * 
     * @see \ref entails(fluent, pworld_ptr) const.
     *  
     * @param[in] to_check: the \ref fluent that has to be checked if entailed in *this*.
     *
     * @return true: \p to_check is entailed in *this*;
     * @return false: \p -to_check is entailed in *this*.*/
    bool entails(fluent to_check) const;
    /** \brief Function that checks the entailment of a conjunctive set of \ref fluent in *this*.
     *
     * The entailment of a conjunctive set of \ref fluent in a pstate is true if the conjunctive set of \ref fluent
     * is entailed by its pointed world (\ref m_pointed).
     * 
     * @see \ref entails(const fluent_set &, pworld_ptr) const.
     *  
     * @param[in] to_check: the conjunctive set of \ref fluent that has to be checked if entailed in *this*.
     *
     * @return true: \p to_check is entailed in *this*;
     * @return false: \p -to_check is entailed in *this*.*/
    bool entails(const fluent_set & to_check) const;
    /**
     *\brief Function that checks the entailment of a DNF \ref fluent_formula in *this*.
     *
     * The entailment of a DNF \ref fluent_formula in a pstate is true if the DNF \ref fluent_formula
     * is entailed by its pointed world (\ref m_pointed).
     * 
     * @see \ref entails(const fluent_formula &, pworld_ptr) const.
     *  
     * @param[in] to_check: the DNF \ref fluent_formula that has to be checked if entailed in *this*.
     *
     * @return true: \p to_check is entailed in *this*;
     * @return false: \p -to_check is entailed in *this*.*/
    bool entails(const fluent_formula & to_check) const;

    /**
     *\brief Function that checks the entailment of a \ref belief_formula in *this*.
     *
     * The entailment of a \ref belief_formula in a pstate is true if the \ref belief_formula
     * is entailed by its pointed world (\ref m_pointed).
     * 
     * @see \ref entails(const belief_formula&, pworld_ptr) const.
     *  
     * @param[in] to_check: the \ref belief_formula that has to be checked if entailed in *this*.
     *
     * @return true: \p to_check is entailed in *this*;
     * @return false: \p -to_check is entailed in *this*.*/
    bool entails(const belief_formula & to_check) const;

    /** \brief Function that builds the initial Kripke structure given the initial conditions.
     *
     * The building of the initial Kripke structure can be done in two different ways:
     *    - A method using a pruning techniques(\ref build_initial_prune).
     *    - A structural build (\ref build_initial_structural).
     * 
     * @see pworld, kedge and initially.
     * 
     * \todo if first method is implemented the add functions in \ref pstore must be changed to not create 
     *       the object every time but just to retrieve the object since all of them are already created.*/
    void build_initial();

    /** \brief Function that applies the transition function on *this* given an action.
     *
     * The transition function is applied accordingly to mA^rho. Check the paper for more information.
     *  
     * @see action.
     *  
     * @param[in] act: The action to be applied on *this*.
     * @return the \ref pstate that results after the execution.
     * 
     * \todo The action must be executable on *this* otherwise it will return a null_ptr.*/
    pstate compute_succ(const action & act) const;

    /** \brief The copy operator.
     *   
     * @param [in] to_copy: the \ref pstate to assign to *this*.
     * @return true: if \p the assignment went ok.
     * @return false: otherwise.*/
    bool operator=(const pstate & to_copy);

    /** \brief Function that prints the information of *this*.*/
    void print() const;
    
        /** \brief Function that prints the information of *this* in a Graphviz file.
         *
         * @param[in] graphviz: the ostream where to print the info of *this*.*/
    void print_graphviz(std::ostream& graphviz) const;


    /** \brief Function that return the sum_set of the two parameters by modifying the first one.
     *
     *  
     * @param[out] to_modify: the set in which is added \p factor2.
     * @param[in] factor2: the set to add to \p to_modify.*/
    template <class T>
    void sum_set(std::set<T> & to_modify, const std::set<T> & factor2) const;
    /** \brief Function that return the set difference of the two parameters by modifying the first one.
     *
     *  
     * @param[out] to_modify: the set from which is removed \p factor2.
     * @param[in] factor2: the set to remove from \p to_modify.*/
    template <class T>
    void minus_set(std::set<T> & to_modify, const std::set<T> & factor2) const;
    
    
    /*fluent_formula get_sensing_effects_if_entailed(const effects_map & map, const pworld_ptr & start) const;*/
};

